-- MySQL Script generated by MySQL Workbench
-- Tue Jan  9 12:10:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NFactoryBlog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NFactoryBlog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NFactoryBlog` DEFAULT CHARACTER SET utf8 ;
USE `NFactoryBlog` ;

-- -----------------------------------------------------
-- Table `NFactoryBlog`.`T_ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFactoryBlog`.`T_ROLES` (
  `ID_ROLE` INT NOT NULL AUTO_INCREMENT,
  `ROLEDESI` VARCHAR(45) NOT NULL,
  `ROLEDEF` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_ROLE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFactoryBlog`.`T_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFactoryBlog`.`T_USERS` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL,
  `USERFNAME` VARCHAR(45) NULL,
  `USERMAIL` VARCHAR(255) NOT NULL,
  `USERPASSWORD` CHAR(40) NOT NULL,
  `USERDATEINS` DATETIME NULL,
  `T_ROLES_ID_ROLE` INT NOT NULL,
  PRIMARY KEY (`ID_USER`, `T_ROLES_ID_ROLE`),
  INDEX `fk_T_USERS_T_ROLES_idx` (`T_ROLES_ID_ROLE` ASC),
  CONSTRAINT `fk_T_USERS_T_ROLES`
    FOREIGN KEY (`T_ROLES_ID_ROLE`)
    REFERENCES `NFactoryBlog`.`T_ROLES` (`ID_ROLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFactoryBlog`.`T_ARTICLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFactoryBlog`.`T_ARTICLES` (
  `ID_ARTICLE` INT NOT NULL AUTO_INCREMENT,
  `ARTTITRE` VARCHAR(45) NOT NULL,
  `ARTCHAPO` VARCHAR(45) NULL,
  `ARTCONTENU` VARCHAR(45) NOT NULL,
  `ARTDATE` DATETIME NULL,
  PRIMARY KEY (`ID_ARTICLE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFactoryBlog`.`T_CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFactoryBlog`.`T_CATEGORIES` (
  `ID_CATEGORIE` INT NOT NULL AUTO_INCREMENT,
  `CATLIBELLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_CATEGORIE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFactoryBlog`.`T_CATEGORIES_has_T_ARTICLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFactoryBlog`.`T_CATEGORIES_has_T_ARTICLES` (
  `T_CATEGORIES_ID_CATEGORIE` INT NOT NULL,
  `T_ARTICLES_ID_ARTICLE` INT NOT NULL,
  PRIMARY KEY (`T_CATEGORIES_ID_CATEGORIE`, `T_ARTICLES_ID_ARTICLE`),
  INDEX `fk_T_CATEGORIES_has_T_ARTICLES_T_ARTICLES1_idx` (`T_ARTICLES_ID_ARTICLE` ASC),
  INDEX `fk_T_CATEGORIES_has_T_ARTICLES_T_CATEGORIES1_idx` (`T_CATEGORIES_ID_CATEGORIE` ASC),
  CONSTRAINT `fk_T_CATEGORIES_has_T_ARTICLES_T_CATEGORIES1`
    FOREIGN KEY (`T_CATEGORIES_ID_CATEGORIE`)
    REFERENCES `NFactoryBlog`.`T_CATEGORIES` (`ID_CATEGORIE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_CATEGORIES_has_T_ARTICLES_T_ARTICLES1`
    FOREIGN KEY (`T_ARTICLES_ID_ARTICLE`)
    REFERENCES `NFactoryBlog`.`T_ARTICLES` (`ID_ARTICLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFactoryBlog`.`T_ARTICLES_has_T_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFactoryBlog`.`T_ARTICLES_has_T_USERS` (
  `T_ARTICLES_ID_ARTICLE` INT NOT NULL,
  `T_USERS_ID_USER` INT NOT NULL,
  `T_USERS_T_ROLES_ID_ROLE` INT NOT NULL,
  PRIMARY KEY (`T_ARTICLES_ID_ARTICLE`, `T_USERS_ID_USER`, `T_USERS_T_ROLES_ID_ROLE`),
  INDEX `fk_T_ARTICLES_has_T_USERS_T_USERS1_idx` (`T_USERS_ID_USER` ASC, `T_USERS_T_ROLES_ID_ROLE` ASC),
  INDEX `fk_T_ARTICLES_has_T_USERS_T_ARTICLES1_idx` (`T_ARTICLES_ID_ARTICLE` ASC),
  CONSTRAINT `fk_T_ARTICLES_has_T_USERS_T_ARTICLES1`
    FOREIGN KEY (`T_ARTICLES_ID_ARTICLE`)
    REFERENCES `NFactoryBlog`.`T_ARTICLES` (`ID_ARTICLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_ARTICLES_has_T_USERS_T_USERS1`
    FOREIGN KEY (`T_USERS_ID_USER` , `T_USERS_T_ROLES_ID_ROLE`)
    REFERENCES `NFactoryBlog`.`T_USERS` (`ID_USER` , `T_ROLES_ID_ROLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
